services:
  app:
    build: .
    container_name: php_app
    restart: always
    volumes:
      - ".:/var/www/html"
    ports:
      - "${APP_PORT:-80}:80"
    depends_on:
      - mysql
    environment:
      DB_DATABASE: "${DB_DATABASE}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USERNAME: "${DB_USERNAME}"

      # - DB_CHARSET="utf8mb4"
      # - DB_COLLATION="utf8mb4_unicode_ci"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "composer install --no-interaction --prefer-dist && apache2-foreground",
      ]

  mysql:
    image: "mysql/mysql-server:8.0"

    ports:
      - "3306:3306"

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      # MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
